# Generated by Django 6.0.7 on 2026-07-28 05:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homepagesettings_overview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
