# Generated by Django 6.0.7 on 2026-07-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mentor_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
