# Generated by Django 6.0.7 on 2026-07-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesettings',
            name='hero_opacity_percentage',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='hero_opacity_percentage',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_opacity_percentage',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='hero_opacity_percentage',
        ),
        migrations.RemoveField(
            model_name='registrationpagesettings',
            name='hero_opacity_percentage',
        ),
        migrations.RemoveField(
            model_name='servicespagesettings',
            name='hero_opacity_percentage',
        ),
    ]
