# Generated by Django 6.0.7 on 2026-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_aboutpagesettings_hero_opacity_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='why_choose_us_badge_text',
            field=models.CharField(blank=True, default='Why Us', max_length=50),
        ),
    ]
