# Generated by Django 6.0.7 on 2026-07-28 07:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homepagesettings_why_choose_us_badge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='about_section_badge_text',
            field=models.CharField(blank=True, default='About Us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_section_content',
            field=tinymce.models.HTMLField(blank=True, default='\n    <h3 style="font-weight: bold; font-size: 1.125rem; margin-bottom: 0.5rem;">Your Gateway to U.S. Trade</h3>\n    <p style="margin-bottom: 1rem;">Trade California supports international businesses, government buyers, distributors, and organizations seeking reliable access to American products and business opportunities.</p>\n    <p style="margin-bottom: 1.5rem;">Our focus is to connect qualified international buyers with U.S.-based suppliers while providing support across sourcing, communication, logistics coordination, product consultancy, and international business development.</p>\n    \n    <h3 style="font-weight: bold; font-size: 1.125rem; margin-bottom: 0.5rem;">Our Core Areas</h3>\n    <ul style="list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1rem;">\n        <li>U.S. Commodity Trading</li>\n        <li>Agriculture & Food Trading</li>\n        <li>Healthcare Products</li>\n    </ul>\n    <ul style="list-style-type: disc; padding-left: 1.5rem; font-weight: bold; margin-bottom: 1rem;">\n        <li>Energy Commodities</li>\n    </ul>\n    <ul style="list-style-type: disc; padding-left: 1.5rem; font-weight: bold; margin-bottom: 1rem;">\n        <li>Industrial Commodities</li>\n    </ul>\n    <ul style="list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1rem;">\n        <li style="font-weight: bold;">Consumer & Lifestyle Products</li>\n        <li>International Business Consultancy</li>\n        <li>U.S. Product Consultancy</li>\n        <li>Logistics Support</li>\n        <li>Contract & Trade Facilitation</li>\n    </ul>\n    '),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='about_section_title',
            field=models.CharField(blank=True, default='About Trade California', max_length=255),
        ),
    ]
