# Generated by Django 6.0.7 on 2026-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homepagesettings_about_section_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagesettings',
            name='catalog_badge_text',
            field=models.CharField(blank=True, default='Global Export Portfolio', max_length=50),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='catalog_subtext',
            field=models.TextField(blank=True, default='Seamlessly navigate our meticulously curated selection of high-value commodities, agricultural products, and industrial resources ready for the global market.'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='catalog_title_highlight',
            field=models.CharField(blank=True, default='Trade Directory', max_length=100),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='catalog_title_prefix',
            field=models.CharField(blank=True, default="California's Premium", max_length=100),
        ),
    ]
