# Generated by Django 6.0.7 on 2026-07-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productspagesettings_catalog_badge_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesPageSettings',
        ),
    ]
