# Generated by Django 6.0.7 on 2026-07-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_servicespagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='about_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/'),
        ),
    ]
