# Generated by Django 6.0.7 on 2026-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_homepagesettings_about_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='bottom_large_image',
            field=models.ImageField(blank=True, help_text='Large image displayed at the bottom of the home page', null=True, upload_to='site/bottom_banner/'),
        ),
    ]
