# Generated by Django 6.0.7 on 2026-07-29 09:20

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_homepagesettings_bottom_large_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_description',
            field=tinymce.models.HTMLField(blank=True, default='<p>Trade California connects international buyers with selected U.S.-based commodities, agricultural products, healthcare products, food and beverages, and other American products.</p><p>We work to facilitate communication between qualified buyers and U.S. suppliers for international trade opportunities.</p>'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='site/trade/'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='site/trade/'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='site/trade/'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='site/trade/'),
        ),
        migrations.AddField(
            model_name='productspagesettings',
            name='trade_title',
            field=models.CharField(blank=True, default='Trading American Products Around the World', max_length=255),
        ),
    ]
