# Generated by Django 6.0.7 on 2026-07-29 09:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productspagesettings_trade_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspagesettings',
            name='trade_image_1',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='trade_image_2',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='trade_image_3',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='trade_image_4',
        ),
        migrations.AlterField(
            model_name='productspagesettings',
            name='trade_description',
            field=ckeditor.fields.RichTextField(blank=True, default='<p>Trade California connects international buyers with selected U.S.-based commodities, agricultural products, healthcare products, food and beverages, and other American products.</p><p>We work to facilitate communication between qualified buyers and U.S. suppliers for international trade opportunities.</p>'),
        ),
        migrations.CreateModel(
            name='TradePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/trade/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_images', to='core.productspagesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
