# Generated by Django 6.0.7 on 2026-07-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_productspagesettings_trade_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspagesettings',
            name='catalog_badge_text',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='catalog_subtext',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='catalog_title_highlight',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='catalog_title_prefix',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='hero_headline',
        ),
        migrations.RemoveField(
            model_name='productspagesettings',
            name='hero_subtext',
        ),
    ]
