# Generated by Django 6.0.7 on 2026-07-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_productspagesettings_catalog_badge_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
    ]
