# Generated by Django 6.0.7 on 2026-08-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_contactpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(blank=True, default='Our Services', max_length=255, null=True)),
                ('hero_subtext', models.TextField(blank=True, default='Professional Business Services', null=True)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('bottom_large_image', models.ImageField(blank=True, help_text='Large dynamic image for the services page', null=True, upload_to='site/services_banner/')),
            ],
            options={
                'verbose_name': 'Services Page Settings',
                'verbose_name_plural': 'Services Page Settings',
            },
        ),
    ]
