# Generated by Django 6.0.7 on 2026-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_servicespagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='emails',
            field=models.CharField(blank=True, help_text='Enter multiple emails separated by commas (e.g. email1@example.com, email2@example.com)', max_length=255),
        ),
    ]
